apiVersion: v1
kind: Namespace
metadata:
  name: security
---
apiVersion: v1
kind: Pod
metadata:
  namespace: security
  name: sample-web-go-multi
  labels:
    app: sample-web-go
spec:
  containers:
  - name: web
    image: naritomojp/sample-web:go-multi