apiVersion: v1
kind: Pod
metadata:
  name: sample-web-private
  labels:
    app: sample-web-private
  namespace: security
spec:
  containers:
  - name: web
    image: naritomojp/sample-web-private:case2
    imagePullPolicy: Always