apiVersion: v1
kind: Pod
metadata:
  name: sample-web
  labels:
    app: sample-web
  namespace: security
spec:
  containers:
  - name: web
    image: naritomojp/sample-web:case2
    imagePullPolicy: Always