apiVersion: v1
kind: Namespace
metadata:
  name: security
---
apiVersion: v1
kind: Pod
metadata:
  name: sample-web
  labels:
    app: sample-web
  namespace: security
spec:
  containers:
  - name: web
    image: naritomojp/sample-web:case1  
---
apiVersion: v1
kind: Service
metadata:
  name: sample-web
  labels:
    app: sample-web
  namespace: security
spec:
  selector:
    app: sample-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80